version: '3'

networks:
    nginx-php81-mysql8-node:

services:

    # nginx
    nginx-service:
        image: nginx:stable-alpine
        container_name: nginx-container
        ports:
            - "8090:80"
        volumes:
            - ./app:/var/www/project:delegated
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php81-service
            - mysql8-service
        networks:
            - nginx-php81-mysql8-node

    # php
    php81-service:
        build:
            context: .
            dockerfile: ./php/Dockerfile
            args:
                - XDEBUG_MODES=debug
                - REMOTE_HOST=host.docker.internal # Host machine IP
                - REMOTE_PORT=9003 # IDE/Editor's listener port
                - IDE_KEY=klipsz # IDE's filter/listener key
        container_name: php81-container
        ports:
            - "9000:9000"
        volumes:
            - ./app:/var/www/project:delegated
            - ./php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
            - ./php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini

        networks:
            - nginx-php81-mysql8-node

    # mysql
    mysql8-service:
        image: mysql:5.7
        container_name: mysql8-container
        ports:
            - "4307:3306"
        volumes:
            - ./mysql:/var/lib/mysql
        command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        restart: always # always restart unless stopped manually
        environment:
            MYSQL_DATABASE: 'symfony_docker'
            # So you don't have to use root, but you can if you like
            MYSQL_USER: 'user'
            # You can use whatever password you like
            MYSQL_PASSWORD: 'secret'
            # Password for root access
            MYSQL_ROOT_PASSWORD: 'secret'
        networks:
            - nginx-php81-mysql8-node

    # node
    node-service:
        build: ./frontend
        ports:
            - "8080:8080"
            - "8081:8081"
        volumes:
            - ./app:/var/www/front:delegated
            - /var/www/front/node_modules/

    mailhog:
        image: 'mailhog/mailhog:latest'
        restart: always
        ports:
            - '8025:8025'
            - '1025:1025'
        networks:
            - nginx-php81-mysql8-node
