<?php

namespace Pixeloid\AppBundle\Repository;

/**
 * JuryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JuryRepository extends \Doctrine\ORM\EntityRepository
{
}
