imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    default_locale:  "%locale%"

    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']


    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        handler_id: session.handler.native_file
        save_path: '%kernel.root_dir%/sessions'
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
        resources:
            - BraincraftedBootstrapBundle:Form:bootstrap.html.twig
    form_themes:
        - 'PixeloidAppBundle:Form:fields.html.twig'


braincrafted_bootstrap:
    less_filter: less
    customize:
        variables_file: %kernel.root_dir%/../src/Pixeloid/AppBundle/Resources/public/less/variables.less
        bootstrap_output: @PixeloidAppBundle/Pixeloid/AppBundle/Resources/public/less/bootstrap.less
    auto_configure:
        knp_paginator: false
        assetic: false


knp_menu:
    twig:  # use "twig: false" to disable the Twig extension and the TwigRenderer
        template: BraincraftedBootstrapBundle:Menu:bootstrap.html.twig
    templating: false # if true, enables the helper for PHP templates
    default_renderer: twig # The renderer to use, list is also available by default

knp_paginator:
    template:
        pagination: BraincraftedBootstrapBundle:Pagination:bootstrap.html.twig

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    encryption: tls
    auth_mode:  login
    # spool:     { type: memory }

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: Pixeloid\UserBundle\Entity\User

ewz_recaptcha:
    public_key:  6LeGdgsTAAAAAETpYR8N7_O5HR9OrrMweeWG2tyd
    private_key: 6LeGdgsTAAAAAGrF8S35qEkQzzcoBnupPMe8gQzd
    locale_key:  %kernel.default_locale%


knp_snappy:
    pdf:
        enabled:    true
        binary:     /usr/local/bin/wkhtmltopdf #"\"C:\\Program Files\\wkhtmltopdf\\bin\\wkhtmltopdf.exe\"" for Windows users
        options:    []
    image:
        enabled:    true
        binary:     /usr/local/bin/wkhtmltoimage #"\"C:\\Program Files\\wkhtmltopdf\\bin\\wkhtmltoimage.exe\"" for Windows users
        options:    []
    temporary_folder: %kernel.cache_dir%/snappy

ivory_ck_editor:
    default_config: my_config
    plugins:
        wordcount:
            path:     "bundles/pixeloidapp/lib/CKEditor_Plugins/wordcount/"
            filename: "plugin.js"
        notification:
            path:     "bundles/pixeloidapp/lib/CKEditor_Plugins/notification/"
            filename: "plugin.js"
    configs:
        my_config:
            extraPlugins: "wordcount"
            language:  '%locale%'
            wordcount:
                showCharCount: true
                countSpacesAsChars: false
                maxWordCount: 3000
                countHTML: false
                lang:  '%locale%'


avalanche_imagine:
    filters:
        carousel:
            type:    thumbnail
            options: { size: [900, 550], mode: outbound, quality: 80, format: png }

hwi_oauth:
    # list of names of the firewalls in which this bundle is active, this setting MUST be set
    firewall_names: [main]
    # target_path_parameter: _destination=index
    resource_owners:
        facebook:
            type:                facebook
            client_id:           "646741755492022"
            client_secret:       "e542acd98e5d3165c221b6436215823c"
            scope:               "email"
            options:
                csrf: true
                # display: popup #dialog is optimized for popup window
                # auth_type: rerequest # Re-asking for Declined Permissions

    # an optional setting to configure a query string parameter which can be used to redirect
    # the user after authentication, e.g. /connect/facebook?_destination=/my/destination will
    # redirect the user to /my/destination after facebook authenticates them.  If this is not
    # set then the user will be redirected to the original resource that they requested, or
    # the base address if no resource was requested.  This is similar to the behaviour of
    # [target_path_parameter for form login](http://symfony.com/doc/2.0/cookbook/security/form_login.html).
    # target_path_parameter: _destination

    # an optional setting to use the HTTP REFERER header to be used in case no
    # previous URL was stored in the session (i.e. no resource was requested).
    # This is similar to the behaviour of
    # [using the referring URL for form login](http://symfony.com/doc/2.0/cookbook/security/form_login.html#using-the-referring-url).
    # use_referer: true

    # here you will add one (or more) configurations for resource owners
    # and other settings you want to adjust in this bundle, just checkout the list below!


deploy:
  staging:
    rsync-options: '-azC --force --delete --progress -h --checksum'
    host: vps.pixeloid.hu
    dir: /var/www/virtual/pixeloid.hu/dev/klipszemle
    user: vu2001
    port: 22
    timeout: 0 # Connection timeout in seconds. 0 for no timeout.
    post_deploy_operations: 
        - app/console cache:clear --env=prod
        - app/console assets:install --env=prod
        - app/console assetic:dump --env=prod    
        - app/console doctrine:schema:update --force --env=prod    
  prod:
    rsync-options: '-azC --force --delete --progress -h --checksum'
    host: vps.pixeloid.hu
    dir: /var/www/virtual/klipszemle.hu/
    user: vu2097
    port: 22
    timeout: 0 # Connection timeout in seconds. 0 for no timeout.
    post_deploy_operations: 
        - app/console cache:clear --env=prod
        - app/console assets:install --env=prod --symlink
        - app/console doctrine:schema:update --force --env=prod    
