imports:
    - { resource: config.yml }

#framework:
#    validation:
#        cache: apc

doctrine:
    dbal:
        host:     "localhost"
        dbname:   "klipszemle"
        user:     "klipszemle"
        password: "klipszemle_12345"

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        console:
            type:  console
