media:
  resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
  prefix: /media

facebook_login:
  path: /check-facebook

# in app/config/routing.yml
craue_config_settings:
  resource: "@CraueConfigBundle/Resources/config/routing/settings.xml"
  prefix: /settings

_translation_webui:
  resource: '@TranslationBundle/Resources/config/routing_webui.yaml'
  prefix: /trans

_translation_profiler:
  resource: '@TranslationBundle/Resources/config/routing_symfony_profiler.yaml'
# config/routes/php_translation.yaml
_translation_edit_in_place:
  resource: '@TranslationBundle/Resources/config/routing_edit_in_place.yaml'
  prefix: /trans

hwi_oauth_redirect:
  resource: "@HWIOAuthBundle/Resources/config/routing/redirect.php"
  prefix:   /oauth-connect

hwi_oauth_connect:
  resource: "@HWIOAuthBundle/Resources/config/routing/connect.php"
  prefix:   /oauth-connect

hwi_oauth_login:
  resource: "@HWIOAuthBundle/Resources/config/routing/login.php"
  prefix:   /oauth-login

