media:
  resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
  prefix: /media

facebook_login:
  path: /login/check-facebook

# in app/config/routing.yml
craue_config_settings:
  resource: "@CraueConfigBundle/Resources/config/routing/settings.xml"
  prefix: /settings
