gallery:
  resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
  prefix: /media/gallery

media:
  resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
  prefix: /media

hwi_oauth_redirect:
  resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
  prefix:   /connect

hwi_oauth_login:
  resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
  prefix:   /connect

hwi_oauth_connect:
  resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
  prefix:   /connect

facebook_login:
  path: /login/check-facebook
