fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /connect

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix:   /connect

hwi_facebook_login:
    pattern: /login/check-facebook
    

pixeloid_app:
    resource: "@PixeloidAppBundle/Resources/config/routing.yml"

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix:   /user

_imagine:
    resource: .
    type:     imagine

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

# sg_datatables_bundle:
#     resource: "@SgDatatablesBundle/Controller/"
#     type:     annotation
