pixeloid_app:
    resource: "@PixeloidAppBundle/Resources/config/routing.yml"

pixeloid_user_manager:
    resource: "@PixeloidUserBundle/Resources/config/routing.yml"
    prefix:   /user

_imagine:
    resource: .
    type:     imagine

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
sg_datatables_bundle:
    resource: "@SgDatatablesBundle/Controller/"
    type:     annotation
