security:

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
    firewalls:
        main:
            pattern: ^/
            form_login:        
                login_path:             fos_user_security_login 
                check_path:             fos_user_security_check
                csrf_provider:          form.csrf_provider
            logout:
                path: fos_user_security_logout
                target: /
            anonymous:  true

            oauth:
                failure_path: /connect
                login_path: /connect
                check_path: /connect
                default_target_path: /vote/
                provider: fos_userbundle
                resource_owners:
                    facebook:           "/login/check-facebook"
                oauth_user_provider:
                    service: pixeloid_app.fosub.user_provider

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
