accomodation:
    path:     /
    defaults: { _controller: "PixeloidAppBundle:Accomodation:index" }

accomodation_show:
    path:     /{id}/show
    defaults: { _controller: "PixeloidAppBundle:Accomodation:show" }

accomodation_new:
    path:     /new
    defaults: { _controller: "PixeloidAppBundle:Accomodation:new" }

accomodation_create:
    path:     /create
    defaults: { _controller: "PixeloidAppBundle:Accomodation:create" }
    requirements: { _method: post }

accomodation_edit:
    path:     /{id}/edit
    defaults: { _controller: "PixeloidAppBundle:Accomodation:edit" }

accomodation_update:
    path:     /{id}/update
    defaults: { _controller: "PixeloidAppBundle:Accomodation:update" }
    requirements: { _method: post|put }

accomodation_delete:
    path:     /{id}/delete
    defaults: { _controller: "PixeloidAppBundle:Accomodation:delete" }
    requirements: { _method: post|delete }
