presentation:
    path:     /
    defaults: { _controller: "PixeloidAppBundle:Presentation:index" }

presentation_show:
    path:     /{id}/show
    defaults: { _controller: "PixeloidAppBundle:Presentation:show" }

presentation_new:
    path:     /new
    defaults: { _controller: "PixeloidAppBundle:Presentation:new" }

presentation_create:
    path:     /create
    defaults: { _controller: "PixeloidAppBundle:Presentation:create" }
    requirements: { _method: post }

presentation_edit:
    path:     /{id}/edit
    defaults: { _controller: "PixeloidAppBundle:Presentation:edit" }

presentation_update:
    path:     /{id}/update
    defaults: { _controller: "PixeloidAppBundle:Presentation:update" }
    requirements: { _method: post|put }

presentation_delete:
    path:     /{id}/delete
    defaults: { _controller: "PixeloidAppBundle:Presentation:delete" }
    requirements: { _method: post|delete }
