<?php

namespace Pixeloid\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AccomodationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccomodationRepository extends EntityRepository
{

	public function getAccomodationsByEvent($eventId)
	{
	    $qb = $this->_em->createQueryBuilder();
	    $qb->select('a, r')
	        ->from('PixeloidAppBundle:Accomodation', 'a')
	        ->join('a.rooms', 'r')
	        ->join('r.event', 'e')
	        ->where('e.id = :event_id')
	        ->setParameter('event_id', $eventId)
	        ->distinct(true)
	    ;

	    return $qb->getQuery()->getResult();
	}

}
