<?php

namespace Pixeloid\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AccomodationReservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccomodationReservationRepository extends EntityRepository
{
}
