<?php

namespace Pixeloid\AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EventRegistrationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRegistrationRepository extends EntityRepository
{
	public function getWinners()
	{	
		return $this->_em->createQuery('SELECT e FROM PixeloidAppBundle:EventRegistration e WHERE e.winner > 0 ORDER BY e.winner ASC')
		                 ->getResult();
	}
}
