-
  title: NEVEZÉS
  items:
    108:
      - Mi a nevezési határidő?
      - 2021. szeptember 13., 24:00.
    109:
      - Nem teljesen egyértelmű. Most akkor milyen időszakban készült klipeket lehet nevezni?
      - Az előző szemle nevezési határidejének vége (2019.09.15.) óta megjelent videókat tudod nevezni. Vagy olyat, amit most a klipszemlén premiereztetnél.
    110:
      - Mi van??? Tényleg nem nevezhetek 2019.09.15. előtt kijött klipet?!
      - Jól látod. Azt az előző klipszemlékre kellett volna nevezned.
    111:
      - Miért nem regisztrálhatok azzal a mailcímmel, ami csak a spamek miatt van?
      - Mert e-mailen szeretnénk veled felvenni a kapcsolatot.
    112:
      - Minek kell a telefonszámom is?
      - Hogy ha az e-mailekre nem válaszolt, akkor rád tudjunk csörögni. Érted, mi van, ha nyertél??
    113:
      - Egyszerre hány klipet nevezhetek? És egy mailcímmel összesen?
      - Bárhány klipet, akár azonos e-mail címről, de ezek külön nevezési folyamatok lesznek. Törekedj rá, hogy a legjobbakat nevezd be. Nincs számbeli korlát, de légy kegyes velünk! 
    114:
      - Publikusak az infók, amiket beírok a jelentkezésbe?
      - A nevezéseddel elfogadod, hogy a klipedet és az arra vonatkozó információkat a szervezés során használhatjuk. Ha van valami titkos benne, amit csak nekünk, szervezőknek szeretnél elárulni, azt a megjegyzésben jelezd!
    115:
      - Milyen videó minősül klipnek?
      - Egy zenei előadó egy bizonyos számára készített videó. Tehát nem koncertfelvétel, vagy állóképpel feltöltött track. Ha bizonytalan vagy, küldd el nekünk, aztán diagnosztizáljuk!
    116:
      - Mit jelent az, hogy „magyar vonatkozású” klip?
      - Azt, hogy az előadó, vagy a rendező, vagy az operatőr magyar.
    117:
      - Mi a „videoklip jelöléséhez szükséges jogcím”, amivel rendelkeznem kell?
      - Ezzel a résszel kijelented, hogy van jogosultságod nevezni a klipet, a többi résztvevő beleegyezésével. Lehetsz az előadó, a menedzsment, a rendező, a kiadó, vagy akár a gyártó, vagy stábtag is.
    118:
      - Ha egyik jogcím sem érvényes rám, úgy is jelentkezhetek?
      - Ha részt vettél a klip készítésében és egyeztettél az érintettekkel, akkor igen.
    119:
      - Akkor ezek szerint nem nevezhetem be a kedvenc klipem?
      - Nem.
    120:
      - És fan videóval lehet nevezni?
      - Sajnos azzal sem.
    121:
      - És cover videóval?
      - Ha ez egy jogilag tisztázott cover, akkor igen.
    122:
      - Miért csak YouTube-linket írhatok be? Vimeóról hallottatok már?
      - Hallottunk, és köszönjük, hogy elfogadod ezt a kritériumot. Ha nem akarod, hogy ott elérhető legyen, töltsd fel unlisted formában.
    123:
      - Nem akarom YouTube-ra tölteni, mehet a klip file-küldőn is?
      - Sajnos nem.
    125:
      - Van az a pipálandó, hogy bekerülhet a rendezvényen forgatott anyagba részlet a klipből. Ez mi?
      - Hogy a klipedből részlet megjelenhet a szemle promóciós anyagaiban, aftermovie-jában, vagy teaser videóiban.
    126:
      - Jól gondolom, hogy ha felhasználtok részletet a klipemből promóra, azért se kapok pénzt?
      - Jól.
    127:
      - Elrontottam valamit az adatlap kitöltésénél, újra kitölthetem?
      - Egy YouTube-linkkel csak egyszer tudsz nevezni. Ha valamit nagyon elrontottál, írj nekünk az info.klipszemle@gmail.com címre.

- 
  title: PREMIEREZÉS
  items:
    129:
      - Most is lesz lehetőség a szemlén premierezni?
      - Igen!
    130:
      - Fasza. De hogy töltsem ki a nevezési űrlapot, ha még nincs linkem a kliphez?
      - Tölts fel egy bármilyen verziót a klipből, vagy egy random linket, és jelezd nekünk külön, hogy az nem a végleges!
    132:
      - Hogyha nem jut be a versenyprogramba a premieres klipem, nem is lesz vetítve?
      - Ha a versenypromramon kívül, külön premiereznénk, abban az esetben felvesszük veled a kapcsolatot!
    133:
      - Az még oké, hogy 2021.10.14. 20:00 előtt nem jelenhet meg a premieres klip, de mi az, hogy nem kerül közönségszavazásra???
      - Ha a közönség meg tudja nézni a szavazáson, akkor az már egy online premier.
    134:
      - És az mi má’, hogy legkésőbb 2021.09.20-ig el kell küldeni a végleges verziót?! Akkor még nem fogunk állni vele sehogy!!!
      - Akkor se parázz, lesz jövőre is szemle! Idén viszont tovább nem tudunk várni rá.

- 
  title: KLIP-BEKÉRÉS
  items:
    135:
      - A nevezés utáni automatikus válaszban van, hogy bekérhetitek a klipet. Mikor és minek?
      - Abban az esetben fogjuk bekérni, a nevezés lezárulta után, ha bekerülsz a vetítési programba.
    136:
      - Idén is tolhatom majd Google Drive-on / Dropboxon / MyAirBridge-en?
      - "Mindenki szerencséjére: NEM! Van már saját felületünk, oda töltsd majd fel, a bekérő levélből minden egyértelműen kiderül!"
    137:
      - És személyesen, vinyón se adhatom oda?
      - Nem.
    138:
      - Volt eddig vmi extra specifikáció, amit sose tudtunk adni. Elég lesz a YouTube-os minőség?
      - A klipből készült legjobb vetíthető minőséget töltsd fel. (Ez a mai világban már nem feltétlenül sok gigás file-okat jelent.)
    139:
      - Szóval nem minden jelölt klip kerül be automatikusan a vetítésre?
      - Nem.
    140:
      - Lehet, hogy azért nem került be a klipem, mert nem 3 perces volt, hanem 8,5? Végig se néztétek, mi?
      - Az egyik kedvenc klipünk három évvel ezelőttről pont nyolc perces, szóval ne rágalmazz, tarrbéla!

- 
  title: RENDEZVÉNY
  items:
    141:
      - Eddig se volt tiszta, hogy mi a különbség a shortlist és a versenyprogram (vetített klipek) között. Mi is?
      - A shortlist az, ami az előválogató eredménye, ez kerül a zsűri elé. A versenyprogram az, amit van is időnk levetíteni a rendezvényen.
    142:
      - Vagyis akkor a kategóriák legjobbjaiból most még rövidebb lista lesz, mint eddig?
      - Annyi klipet vetítünk, amennyit tudunk. Ez kategóriánként 3-5-7-et jelent általában.
    143:
      - Tuti csak a kategóriák legjobbjait vetítitek, mutyizni se lehet?
      - Nagyon sok más helyen lehet mutyizni Magyarországon. Ajánljuk azokat.
    144:
      - Ha bekerül a klip a versenyprogramba, ott kell lennünk az Akvában?
      - A díjátadóra mindenképp gyere el, mert akkor már nagy rá az esély, hogy nyerni fogsz.
    145:
      - Nyertes klipenként hányan jöhetünk?
      - Erről kaptok majd értesítést.
    146:
      - És ha odamegyünk, kapunk legalább belépőt meg piát ingyen?
      - A rendezvény ingyenes, bárki jöhet, de idén csak a meghívottak mehetnek be a NagyHall-ba. Viszont a versenyprogramba jutottak kapnak némi Absolutot ! ;)
    148:
      - Ha nyerünk, de nem tudunk ott lenni az eseményen, odaadjátok a díjat másnak?
      - Inkább legyetek ott. Ha orvosi papírotok van, akkor úgyis egyeztetünk előtte.
