monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
            excluded_http_codes: [404, 405]
            buffer_size: 50 # How many messages should be saved? Prevent memory leaks
        nested:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: error
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
        deprecation:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.deprecations.log"
        deprecation_filter:
            type: filter
            handler: deprecation
            max_level: info
            channels: ["php"]
        symfony_mailer:
            type:       symfony_mailer
            from_email: 'info.klipszemle@gmail.com'
            to_email:   'olah.gergely@pixeloid.hu'
            # or list of recipients
            # to_email:   ['dev1@example.com', 'dev2@example.com', ...]
            subject:    'A Klipszemle Error Occurred! %%message%%'
            level:      critical
            formatter:  monolog.formatter.html
            content_type: text/html
        deduplicated:
            type: deduplication
            # the time in seconds during which duplicate entries are discarded (default: 60)
            time: 10
            handler: symfony_mailer

# monolog:
#     handlers:
#         main:
#             type:         fingers_crossed
#             # 500 errors are logged at the critical level
#             action_level: critical
#             # to also log 400 level errors (but not 404's):
#             # action_level: error
#             # excluded_404s:
#             #     - ^/
#             handler:      deduplicated
#         deduplicated:
#             type:    deduplication
#             handler: swift
