
pixeloid_app_eventregistration:
    resource: "@PixeloidAppBundle/Resources/config/routing/eventregistration.yml"
    prefix:   /eventregistration

pixeloid_app_eventregistration_annotation:
    resource: "@PixeloidAppBundle/Controller/EventRegistrationController.php"
    prefix:   /eventregistration
    type:     annotation

# pixeloid_app_vote:
#     resource: "@PixeloidAppBundle/Controller/VoteController.php"
#     prefix:   /vote
#     type:     annotation


pixeloid_app_presentation:
    resource: "@PixeloidAppBundle/Resources/config/routing/presentation.yml"
    prefix:   /presentation


pixeloid_app_index:
    path:     /
    defaults: { _controller: PixeloidAppBundle:Default:index, event: "ESCPR" }


pixeloid_app_privacy:
    path:     /privacy
    defaults: { _controller: PixeloidAppBundle:Default:privacy }
