

pixeloid_app_eventregistration_annotation:
    resource: "@PixeloidAppBundle/Controller/EventRegistrationController.php"
    prefix:   /nevezes
    type:     annotation
pixeloid_app_default:
    resource: "@PixeloidAppBundle/Controller/DefaultController.php"
    prefix:   /
    type:     annotation

# pixeloid_app_vote:
#     resource: "@PixeloidAppBundle/Controller/VoteController.php"
#     prefix:   /vote
#     type:     annotation


pixeloid_app_presentation:
    resource: "@PixeloidAppBundle/Resources/config/routing/presentation.yml"
    prefix:   /presentation


pixeloid_app_privacy:
    path:     /privacy
    defaults: { _controller: PixeloidAppBundle:Default:privacy }
