services:
  pixeloid_app.form.eventRegistration:
    class: Pixeloid\AppBundle\Form\EventRegistrationType
    tags:
      - { name: form.type, alias: eventRegistration }

  pixeloid_app.flow.eventRegistration:
    class: Pixeloid\AppBundle\Form\EventRegistrationFlow
    parent: craue.form.flow
    scope: request
    calls:
      - [ setFormType, [ "@pixeloid_app.form.eventRegistration" ] ]