services:

  pixeloid_app.form.eventRegistration:
    class: Pixeloid\AppBundle\Form\EventRegistrationType
    tags:
      - { name: form.type, alias: eventRegistration }

  pixeloid_app.flow.eventRegistration:
    class: Pixeloid\AppBundle\Form\EventRegistrationFlow
    parent: craue.form.flow
    scope: request
    calls:
      - [ setFormType, [ "@pixeloid_app.form.eventRegistration" ] ]

  # pixeloid_app.datatable.eventregistration:
  #     class: Pixeloid\AppBundle\Datatables\EventRegistrationDatatable
  #     parent: sg_datatables.datatable.abstract

  # pixeloid_app.datatable.shortlist:
  #     class: Pixeloid\AppBundle\Datatables\ShortlistDatatable
  #     parent: sg_datatables.datatable.abstract

  pixeloid_app.twig_extension:
      class: Pixeloid\AppBundle\Twig\AppExtension
      public: false
      tags:
          - { name: twig.extension }

  pixeloid_app.fosub.user_provider:
      class:        Pixeloid\AppBundle\Security\User\Provider\OAuthUserProvider
      arguments: ['@fos_user.user_manager', { facebook: facebook_id }]
