services:
  pixeloid_app.form.eventRegistration:
    class: Pixeloid\AppBundle\Form\EventRegistrationType
    tags:
      - { name: form.type, alias: eventRegistration }

  pixeloid_app.flow.eventRegistration:
    class: Pixeloid\AppBundle\Form\EventRegistrationFlow
    parent: craue.form.flow
    scope: request
    calls:
      - [ setFormType, [ "@pixeloid_app.form.eventRegistration" ] ]

  pixeloid_app.form.presentation:
    class: Pixeloid\AppBundle\Form\PresentationType
    tags:
      - { name: form.type, alias: presentation }

  pixeloid_app.flow.presentation:
    class: Pixeloid\AppBundle\Form\PresentationFlow
    parent: craue.form.flow
    scope: request
    calls:
      - [ setFormType, [ "@pixeloid_app.form.presentation" ] ]

  pixeloid_app.datatable.eventregistration:
      class: Pixeloid\AppBundle\Datatables\EventRegistrationDatatable
      parent: sg_datatables.datatable.abstract
  pixeloid_app.twig_extension:
      class: Pixeloid\AppBundle\Twig\AppExtension
      public: false
      tags:
          - { name: twig.extension }
