<?php

namespace App\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EventRegistrationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRegistrationRepository extends EntityRepository
{
	public function getAllForVoting()
	{
		return $this->getEntityManager()
		    ->createQuery(
		        'SELECT e FROM App:EventRegistration e WHERE e.voteable = TRUE'
		    )
		    ->getResult();
	}
	public function get()
	{
		return $this->_em->createQuery('SELECT e FROM App:EventRegistration e WHERE e.winner > 0 ORDER BY e.winner ASC')
		                 ->getResult();
	}


	public function hasAlreadyVoted(User $user, EventRegistration $video )
	{
		$result = $this->_em->createQuery('
			SELECT v
			FROM App:Vote v 
			LEFT JOIN v.eventRegistration e
			LEFT JOIN v.user u
			WHERE 
					e = :e 
				AND u = :u ')

			->setParameters(array(
				'e' => $video,
				'u' => $user,
			))
		                 ->getArrayResult();
		     return count($result) > 0;
	}

	public function getRatings(\DateTime $from, MovieCategory $cat): ?Array
	{
	    $res = $this->createQueryBuilder('er')
	        ->select('er.id, er.video_url, er.author,  er.songtitle, count(juryvotes.id) AS numvotes, sum(juryvotes.rate) AS sumvotes, sum(juryvotes.specialprize) AS sumspecial, sum(juryvotes.best) AS sumbest, avg(juryvotes.rate) AS avgrating')
	        ->leftJoin('er.juryvotes', 'juryvotes')
	        ->leftJoin('er.moviecategories', 'erc')
	        ->leftJoin('erc.category', 'mc')
	        ->andWhere('er.created > :created')
	        ->andWhere('er.shortlist = 1')
	        ->andWhere('mc = :cat')
	        ->setParameter('created', $from)
	        ->setParameter('cat', $cat)
	        ->groupBy('er.id')
	        ->orderBy('sumvotes', 'DESC')
	        ->getQuery()
	        ->getResult()
	    ;

	    return $res;
	}


	public function getOnshow(\DateTime $from): ?Array
	{
	    $res = $this->createQueryBuilder('er')
	        ->select('er')
	        ->andWhere('er.created > :created')
	        ->andWhere('er.onshow = 1')
	        ->setParameter('created', $from)
	        ->getQuery()
	        ->getResult()
	    ;

	    return $res;
	}


}
