sonata_media:
  # if you don't use default namespace configuration
  #class:
  #    media: MyVendor\MediaBundle\Entity\Media
  #    gallery: MyVendor\MediaBundle\Entity\Gallery
  #    gallery_has_media: MyVendor\MediaBundle\Entity\GalleryHasMedia
  db_driver: doctrine_orm # or doctrine_mongodb, doctrine_phpcr it is mandatory to choose one here
  default_context: default # you need to set a context
  contexts:
    default:  # the default context is mandatory
      providers:
        - sonata.media.provider.image

      formats:
        small: { width: 100 , quality: 70}
        med: { width: 400 , quality: 70}
        big:   { width: 900 , quality: 70}

  cdn:
    server:
      path: /uploads/media # http://media.sonata-project.org/

  filesystem:
    local:
      directory: '%kernel.project_dir%/public/uploads/media'
      create:     true

  class:
    media: App\Entity\SonataMedia
    gallery: App\Entity\SonataGallery
    gallery_has_media: App\Entity\SonataGalleryItem

